### Page d'acceuil
GET http://localhost:4000/admin/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlzQWRtaW4iOm51bGwsImlhdCI6MTYyNDQ2Nzc4OCwiZXhwIjoxNjI0NDcxMzg4fQ.SLeURkAUDyynrcWpAB_eY3NMR95WdXp_WtLZLExogno

### Page des jeux
GET http://localhost:4000/admin/jeux
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI



### Insert  des jeux
POST  http://localhost:4000/admin/jeux
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "label": "Saboteur",
    "duration": 30,
    "player_min": 1,
    "player_max": 2,
    "age_min": 8,
    "picture": "https://zupimages.net/up/21/24/ttxa.jpg",
    "year": 2017,
    "describe":"",
    "editor_id": 6,
    "author_id": [1],
    "theme_id": [2],
    "category_id": [6]
}


### Update  des jeux
Patch  http://localhost:4000/admin/jeux/60
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "label": "Saboteur",
    "duration": 30,
    "player_min": 1,
    "player_max": 2,
    "age_min": 8,
    "picture": "https://zupimages.net/up/21/24/ttxa.jpg",
    "year": 2017,
    "describe":"",
    "editor_id": 1
}

### Delete  des jeux
DELETE http://localhost:4000/admin/jeux/60


### Page des Editors
GET  http://localhost:4000/admin/editor
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI

### Insert  des editors
POST  http://localhost:4000/admin/editor
Content-Type: application/json

{
    "label": "Artipia Games"
}

### Update  des editor
Patch  http://localhost:4000/admin/editor/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "label": "Amigo"
}

### Delete  des editor
DELETE   http://localhost:4000/admin/editor/1



### Page des themes
GET  http://localhost:4000/admin/theme
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQzNjUyMiwiZXhwIjoxNjI0NDQwMTIyfQ.j7mSWT15_sjH367Vzsgwx-DiMRj92FSbf_Jx1izVV9I

### Insert  des themes
POST  http://localhost:4000/admin/theme
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQzNjUyMiwiZXhwIjoxNjI0NDQwMTIyfQ.j7mSWT15_sjH367Vzsgwx-DiMRj92FSbf_Jx1izVV9I
Content-Type: application/json

{
    "label": "Science fiction"
}

### Update  des editor
Patch  http://localhost:4000/admin/theme/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "label": "Histoire"
}

### Delete  des themes
DELETE   http://localhost:4000/admin/theme/1



### Page des category
GET  http://localhost:4000/admin/category


### Insert  des categories
POST  http://localhost:4000/admin/category
Content-Type: application/json

{
    "label": "Fantaisie"
}

### Update  des category
Patch  http://localhost:4000/admin/category/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "label": "Histoire"
}


### Delete  des category
DELETE   http://localhost:4000/admin/category/1


### Page des auteur
GET  http://localhost:4000/admin/author


### Insert  des auteurs
POST  http://localhost:4000/admin/author
Content-Type: application/json

{
    "firstname": "Regis",
    "lastname": "Bonnessée"

}

### Update  des aueurs
Patch  http://localhost:4000/admin/author/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "firstname": "Regis",
    "lastname": "Bonnessée"
}


### Delete  des author
DELETE   http://localhost:4000/admin/author/88




### Page des users
GET http://localhost:4000/admin/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI

### Delete des users
DELETE  http://localhost:4000/admin/users/4


### Page des event
GET http://localhost:4000/admin/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQzODAxNSwiZXhwIjoxNjI0NDQxNjE1fQ.pCNn8D7ls7wOOz_GPINDBwJryAItgIE-SnwC1NbNIiM

### Delete des event
DELETE  http://localhost:4000/admin/event/2

-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------

### Page d'acceuil
GET  https://playrfindr.herokuapp.com/admin/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI

### Page des jeux
GET  https://playrfindr.herokuapp.com/admin/jeux
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI


### Insert  des jeux
POST  https://playrfindr.herokuapp.com/admin/jeux
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDE5NTIwMCwiZXhwIjoxNjI0MTk4ODAwfQ.Qw6inJbBg8n3cM-zvmKLnf6Ve3XEQgJynagLKLiW_9M
Content-Type: application/json

{
    "label": "Dixit",
    "duration": "30",
    "player_min": "3",
    "player_max": "6",
    "age_min": "8",
    "picture":"https://zupimages.net/up/21/24/3io7.png",
    "year":"2009",
    "describe":"Dixit est un jeu de société qui fait appel à l'imagination. Il se joue en famille et favorise la créativité",
    "editor_id": 2
}



### Update  des jeux
Patch   https://playrfindr.herokuapp.com/admin/jeux/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDM0ODA0NywiZXhwIjoxNjI0MzUxNjQ3fQ.QFISHENtkTTVFN6otdmQenA2XKqeDK3EvGgyqaiPvtg
Content-Type: application/json

{

    "picture": "https://www.zupimages.net/up/21/24/3io7.png"
}

### Delete  des jeux
DELETE  https://playrfindr.herokuapp.com/admin/jeux/60


### Page des Editors
GET   https://playrfindr.herokuapp.com/admin/editor
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI

### Insert  des editors
POST   https://playrfindr.herokuapp.com/admin/editor
Content-Type: application/json

{
    "label": "Artipia Games"
}

### Update  des editor
Patch   https://playrfindr.herokuapp.com/admin/editor/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "label": "Amigo"
}

### Delete  des editor
DELETE    https://playrfindr.herokuapp.com/admin/editor/1



### Page des themes
GET   https://playrfindr.herokuapp.com/admin/theme
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI

### Insert  des themes
POST   https://playrfindr.herokuapp.com/admin/theme
Content-Type: application/json

{
    "label": "Histoire"
}

### Update  des editor
Patch   https://playrfindr.herokuapp.com/admin/theme/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "label": "Histoire"
}

### Delete  des themes
DELETE    https://playrfindr.herokuapp.com/admin/theme/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDI1OTMyNSwiZXhwIjoxNjI0MjYyOTI1fQ.5IUZdzSHnvXmz4dtdG9qdZPTvsnYhonEFN1boMEmdf8


### Page des category
GET   https://playrfindr.herokuapp.com/admin/category
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI

### Insert  des categories
POST   https://playrfindr.herokuapp.com/admin/category
Content-Type: application/json

{
    "label": "Fantaisie"
}

### Update  des category
Patch   https://playrfindr.herokuapp.com/admin/category/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDEwNjMzMywiZXhwIjoxNjI0MTA5OTMzfQ.n9FWPeXKz2HJVLnKRlhFGvEl8fqk6DUlIPmfUUiD768
Content-Type: application/json

{
    "label": "Histoire"
}


### Delete  des category
DELETE    https://playrfindr.herokuapp.com/admin/category/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDI1OTMyNSwiZXhwIjoxNjI0MjYyOTI1fQ.5IUZdzSHnvXmz4dtdG9qdZPTvsnYhonEFN1boMEmdf8

### Page des auteur
GET   https://playrfindr.herokuapp.com/admin/author
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ2NjEwOCwiZXhwIjoxNjI0NDY5NzA4fQ.-REH-E-bqnvwYnYhApOdNh5X23kU6caHJz6xYfQzSoM

### Insert  des auteurs
POST   https://playrfindr.herokuapp.com/admin/author/78
Content-Type: application/json

{
    "firstname": "Paul",
    "lastname": "Leconard"

}

### Update  des aueurs
Patch   https://playrfindr.herokuapp.com/admin/author/78
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ2NjEwOCwiZXhwIjoxNjI0NDY5NzA4fQ.-REH-E-bqnvwYnYhApOdNh5X23kU6caHJz6xYfQzSoM
Content-Type: application/json

{
    "firstname": "Paul",
    "lastname": "Leconard"
}


### Delete  des category
DELETE    https://playrfindr.herokuapp.com/admin/category/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDI1OTMyNSwiZXhwIjoxNjI0MjYyOTI1fQ.5IUZdzSHnvXmz4dtdG9qdZPTvsnYhonEFN1boMEmdf8



### Page des users
GET  https://playrfindr.herokuapp.com/admin/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDI1OTMyNSwiZXhwIjoxNjI0MjYyOTI1fQ.5IUZdzSHnvXmz4dtdG9qdZPTvsnYhonEFN1boMEmdf8


### Delete des users 

DELETE  https://playrfindr.herokuapp.com/admin/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDI1OTMyNSwiZXhwIjoxNjI0MjYyOTI1fQ.5IUZdzSHnvXmz4dtdG9qdZPTvsnYhonEFN1boMEmdf8


###Event

GET https://playrfindr.herokuapp.com/admin/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYyNDQ0MzU1NCwiZXhwIjoxNjI0NDQ3MTU0fQ.5B6nfyuJu3vOznSMsoYXZbLY4ufPZdiODSa4ETiVHiI
