### resource not found
GET https://playrfindr.herokuapp.com/api/null

### Page d'acceuil
GET https://playrfindr.herokuapp.com/api/

### Page d'acceuil
GET http://localhost:4000/api/

### Récupération de tout les jeux avec les themes et catégories
GET https://playrfindr.herokuapp.com/api/jeux

### Récupération de tout les jeux
GET https://playrfindr.herokuapp.com/api/games

### Récupération de tout les themes
GET https://playrfindr.herokuapp.com/api/themes

### Récupération de toute les categories
GET https://playrfindr.herokuapp.com/api/categories

### Récupération de tout les evenements
GET https://playrfindr.herokuapp.com/api/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODM3NzYyLCJleHAiOjE2MjM4NDEzNjJ9.qVAY_Mz3T5q3fv-am86rFQdkRAM0FihF_Nshz1Hr91s

### Récupération des événements
GET http://localhost:4000/api/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODM3NzYyLCJleHAiOjE2MjM4NDEzNjJ9.qVAY_Mz3T5q3fv-am86rFQdkRAM0FihF_Nshz1Hr91s
### Récupération d'un événement
GET http://localhost:4000/api/event/11
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODMyMDkzLCJleHAiOjE2MjM4MzU2OTN9.4WGue_sQLGahpuD3e0pQ3_E8HTlz3KLLCoH0NC5LluQ

### Récupération des messages
GET http://localhost:4000/api/messagerie
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODM2MTc0LCJleHAiOjE2MjM4Mzk3NzR9.LWjzgMNE_QtCX8XWmtOq5Sd0WdC6poAThX2L-GEQKXs

### Récupération des départements
GET http://localhost:4000/api/departements

### Récupération des départements
GET https://playrfindr.herokuapp.com/api/departements

### Récupération d'un jeu
GET https://playrfindr.herokuapp.com/api/jeu/1

### Récupération d'un jeu
GET http://localhost:4000/api/jeu/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODMyMDkzLCJleHAiOjE2MjM4MzU2OTN9.4WGue_sQLGahpuD3e0pQ3_E8HTlz3KLLCoH0NC5LluQ

### Récupération d'un jeu
GET http://localhost:4000/api/jeu/6

### Récupération d'un utilisateur
GET https://playrfindr.herokuapp.com/api/profil/3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTY5NDUsImV4cCI6MTYyMzc2MDU0NX0.u2ZSeMAiSAuGICXnesJy0x66zt8sjRt4l5Hp0ou6

### Récupération d'un utilisateur
GET http://localhost:4000/api/profil/3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTY5NDUsImV4cCI6MTYyMzc2MDU0NX0.u2ZSeMAiSAuGICXnesJy0x66zt8sjRt4l5Hp0oababab

### Récupération de la collection d'un utilisateur
GET https://playrfindr.herokuapp.com/api/profil/3/collection
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTEzOTYsImV4cCI6MTYyMzc1NDk5Nn0.GaBew1SaWtLDL5ntO7ormhGdKSCKKbQT1bgWBP5mTpk

### Ajout d'un jeu a une collection
POST http://localhost:4000/api/profil/3/collection/1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTEzOTYsImV4cCI6MTYyMzc1NDk5Nn0.GaBew1SaWtLDL5ntO7ormhGdKSCKKbQT1bgWBP5mTpk

### Ajout d'un jeu a une collection
POST https://playrfindr.herokuapp.com/api/profil/3/collection/2

### Ajout d'un utilisateur
POST https://playrfindr.herokuapp.com/api/inscription
Content-Type: application/json

{
    "firstname": "Dimitri",
    "lastname": "Guillon",
    "email": "Dimitriguillon@gmail.com",
    "password": "123456",
    "passwordConfirm": "123456",
    "birthdate": "1995-07-18",
    "department_id": 36,
    "is_admin": true,
    "theme_id": [1, 6, 2],
    "category_id": [2, 9, 12]
}
### Ajout d'un utilisateur

POST http://localhost:4000/api/inscription
Content-Type: application/json

{
    "firstname": "Dimitri",
    "lastname": "Guillon",
    "email": "Dimguillon@gmail.com",
    "password": "36Flip93",
    "passwordConfirm": "36Flip93",
    "birthdate": "1995-07-18",
    "department_id": 36,
    "is_admin": true,
    "theme_id": [1, 6, 2],
    "category_id": [2, 9, 12]
}

### Ajout d'un evenement
POST http://localhost:4000/api/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODM3NzYyLCJleHAiOjE2MjM4NDEzNjJ9.qVAY_Mz3T5q3fv-am86rFQdkRAM0FihF_Nshz1Hr91s
Content-Type: application/json

{
    "label": "Partie de Mysterium",
    "content": "Petite partie de Mysterium",
    "date": "2021-09-12",
    "location": "84, rue de la monnaie 59800 Lille",
    "max_player": 7,
    "user_id": 63
}


### Ajout d'un evenement
POST https://playrfindr.herokuapp.com/api/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODM3NzYyLCJleHAiOjE2MjM4NDEzNjJ9.qVAY_Mz3T5q3fv-am86rFQdkRAM0FihF_Nshz1Hr91s
Content-Type: application/json

{
    "label": "Partie de Mysterium",
    "content": "Petite partie de Mysterium",
    "date": "2021-09-12",
    "location": "84, rue de la monnaie 59800 Lille",
    "max_player": 7,
    "user_id": 2
}


### Récuperation d'un utilisateur
POST https://playrfindr.herokuapp.com/api/connexion
Content-Type: application/json

{
    "email": "Dimitriguillon@gmail.com",
    "password": "123456"
 
}

### Récuperation d'un utilisateur
POST http://localhost:4000/api/connexion
Content-Type: application/json

{
    "email": "dimguillon@gmail.com",
    "password": "36Flip93"
 
}

### Ajout d'un utilisateur a un event
POST http://localhost:4000/api/event/35
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTEzOTYsImV4cCI6MTYyMzc1NDk5Nn0.GaBew1SaWtLDL5ntO7ormhGdKSCKKbQT1bgWBP5mTpk

### Update d'un utilisateur
PATCH https://playrfindr.herokuapp.com/api/profil/3
Content-Type: application/json

{
    "lastname": "Martin"
}


### Suppression d'un utilisateur a un event
PATCH http://localhost:4000/api/event/6
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NjQzMjMsImV4cCI6MTYyMzc2NzkyM30.xmE2yK9tLcWdc6fXDDu_cbPcNLC4nN4AzctzBA1MJ8s

### delete d'un utilisateur
DELETE https://playrfindr.herokuapp.com/api/profil/72



### Suppression d'un event
DELETE  http://localhost:4000/api/event/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODM3NzYyLCJleHAiOjE2MjM4NDEzNjJ9.qVAY_Mz3T5q3fv-am86rFQdkRAM0FihF_Nshz1Hr91s

### Suppression d'un event
DELETE  https://playrfindr.herokuapp.com/api/event/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQyLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODM3NzYyLCJleHAiOjE2MjM4NDEzNjJ9.qVAY_Mz3T5q3fv-am86rFQdkRAM0FihF_Nshz1Hr91s


### Delete d'un jeux d'une collection
DELETE http://localhost:4000/api/profil/3/collection/6
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTEzOTYsImV4cCI6MTYyMzc1NDk5Nn0.GaBew1SaWtLDL5ntO7ormhGdKSCKKbQT1bgWBP5mTpk

### Delete d'un jeux d'une collection
DELETE https://playrfindr.herokuapp.com/api/profil/1/collection/6
