### resource not found
GET https://playrfindr.herokuapp.com/api/null

### Page d'acceuil
GET https://playrfindr.herokuapp.com/api/

### Page d'acceuil
GET http://localhost:4000/api/

### Récupération de tout les jeux avec les themes et catégories
GET https://playrfindr.herokuapp.com/api/jeux

### Récupération de tout les jeux
GET https://playrfindr.herokuapp.com/api/games

### Récupération de tout les themes
GET https://playrfindr.herokuapp.com/api/themes

### Récupération de toute les categories
GET https://playrfindr.herokuapp.com/api/categories

### Récupération de tout les evenements
GET https://playrfindr.herokuapp.com/api/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjI0MDAzNzMzLCJleHAiOjE2MjQwMDczMzN9.o8YTOoHcAb4UhruWYO93AAl0BNzDJR8Kcby-sLf789w

### Récupération des événements
GET http://localhost:4000/api/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjI0MDEwODE0LCJleHAiOjE2MjQwMTQ0MTR9.1Qf39JfaB679TkwReVifScKQq7nf5efBn4olvidIV4U

### Récupération des messages
GET http://localhost:4000/api/messagerie
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjI0MDAzNzMzLCJleHAiOjE2MjQwMDczMzN9.o8YTOoHcAb4UhruWYO93AAl0BNzDJR8Kcby-sLf789w

### Récupération des départements
GET http://localhost:4000/api/departements

### Récupération des départements
GET https://playrfindr.herokuapp.com/api/departements

### Récupération d'un jeu
GET https://playrfindr.herokuapp.com/api/jeu/1

### Récupération d'un jeu
GET http://localhost:4000/api/jeu/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzODMyMDkzLCJleHAiOjE2MjM4MzU2OTN9.4WGue_sQLGahpuD3e0pQ3_E8HTlz3KLLCoH0NC5LluQ

### Récupération d'un jeu
GET http://localhost:4000/api/jeu/6

### Récupération d'un utilisateur
GET https://playrfindr.herokuapp.com/api/profil/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQwMTUwMDUsImV4cCI6MTYyNDAxODYwNX0.oWKtrTucgPRhZUhPtEsx4BoRpMRql1_taQOHA4nElK4

### Récupération d'un utilisateur
GET http://localhost:4000/api/profil/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQwMTU0OTQsImV4cCI6MTYyNDAxOTA5NH0.K7wMQFoF-E-dQ3C2eC9ftvxTwuzPV6nwZV25jL8gs2I

### Récupération de la collection d'un utilisateur
GET https://playrfindr.herokuapp.com/api/profil/3/collection
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTEzOTYsImV4cCI6MTYyMzc1NDk5Nn0.GaBew1SaWtLDL5ntO7ormhGdKSCKKbQT1bgWBP5mTpk

### Récupération des messages
GET http://localhost:4000/api/messagerie
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY3LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzOTQwNzYwLCJleHAiOjE2MjM5NDQzNjB9.1kV8yWte0rnj8YMFDJg6zqouTBbEvbhHGA0nbGUzqpY

### Ajout d'un jeu a une collection
POST http://localhost:4000/api/profil/3/collection/1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTEzOTYsImV4cCI6MTYyMzc1NDk5Nn0.GaBew1SaWtLDL5ntO7ormhGdKSCKKbQT1bgWBP5mTpk

### Ajout d'un jeu a une collection
POST https://playrfindr.herokuapp.com/api/profil/3/collection/2

### Ajout d'un utilisateur
POST https://playrfindr.herokuapp.com/api/inscription
Content-Type: application/json

{
    "firstname": "Dimitri",
    "lastname": "Martin",
    "email": "dimitri@gmail.com",
    "password": "123456",
    "passwordConfirm": "123456",
    "birthdate": "1995-07-19",
    "department_id": 36,
    "is_admin": true,
    "theme_id": [1, 6, 2],
    "category_id": [2, 9, 12]
}
### Ajout d'un utilisateur
POST http://localhost:4000/api/inscription
Content-Type: application/json

{
    "firstname": "Dimitri",
    "lastname": "Maite",
    "email": "jabaa@gmail.com",
    "password": "36Flip93",
    "passwordConfirm": "36Flip93",
    "birthdate": "1995-07-18",
    "department_id": 76,
    "is_admin": true,
    "theme_id": [1, 6, 2],
    "category_id": [2, 9, 12]
}

### Ajout d'un evenement
POST http://localhost:4000/api/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjI0MDEwODE0LCJleHAiOjE2MjQwMTQ0MTR9.1Qf39JfaB679TkwReVifScKQq7nf5efBn4olvidIV4U
Content-Type: application/json

{
    "label": "Partie de Mysterium",
    "content": "Petite partie de Mysterium",
    "date": "2021-09-12",
    "number_address": 84,
    "address": "rue de la bicyclette",
    "town": "Marseille",
    "max_player": 7,
    "user_id": 67
}

### Ajout d'un evenement
POST https://playrfindr.herokuapp.com/api/event
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQwMTQ2ODAsImV4cCI6MTYyNDAxODI4MH0.0_ogS_XQ298jLBLeQHyDgPD_j9Lhpqw39ke494VY0UI
Content-Type: application/json

{
   "label": "Partie de Mysterium",
    "content": "Petite partie de Mysterium",
    "date": "2021-09-12",
    "number_address": 13000,
    "address": "84 rue de la bicyclette",
    "town": "Marseille",
    "max_player": 7,
    "user_id": 2
}


### Récuperation d'un utilisateur
POST https://playrfindr.herokuapp.com/api/connexion
Content-Type: application/json

{
    "email": "dimitri@gmail.com",
    "password": "123456"
 
}

### Récuperation d'un utilisateur
POST http://localhost:4000/api/connexion
Content-Type: application/json

{
    "email": "jab@gmail.com",
    "password": "123456"
 
}


### Envoi  d'un message
POST http://localhost:4000/api/messagerie/75
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY3LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjI0MDAwOTc1LCJleHAiOjE2MjQwMDQ1NzV9.XnX9sPaZRqNcWmMacIfc_2IMLobl4OYpi3szGXZMwLo
Content-Type: application/json

{
    "content": "Bonjour, Un whisky ? "
}

### Ajout d'un utilisateur a un event
POST http://localhost:4000/api/event/41
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc5LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzOTM5MjUwLCJleHAiOjE2MjM5NDI4NTB9.9iFSH_5IANXEBFw_EpW7mC7JP9PJKkkmMv7zgA6gd8E

### Ajout d'un utilisateur a un event
POST https://playrfindr.herokuapp.com/api/event/55
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzOTM3ODI1LCJleHAiOjE2MjM5NDE0MjV9.2QJe0KJlvCQzRMF0IY9cCv09e4-5mxKGAfT4bnmjKFU

### Update d'un utilisateur
PATCH https://playrfindr.herokuapp.com/api/profil/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQwMTQxNTEsImV4cCI6MTYyNDAxNzc1MX0.GBUwh8nYoue44DD-S3ngde-bo5mSEe1ghajBrt1wcx4
Content-Type: application/json

{
    "firstname": "Dim",
    "lastname": "Martin",
    "department_id": 20
}


### Update d'un utilisateur
PATCH http://localhost:4000/api/profil/81
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgzLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjI0MDE2NTQxLCJleHAiOjE2MjQwMjAxNDF9.wFLKMd4ieNinzNfstmZ8XVZlTdGXF7IZI9vXoMD_szA
Content-Type: application/json

{
    "firstname": "Dim",
    "lastname": "Martin",
    "department_id": 20,
    "password": "123456",
    "passwordConfirm": "123456"
}

### Suppression d'un utilisateur a un event
PATCH http://localhost:4000/api/event/41
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc5LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzOTM5MjUwLCJleHAiOjE2MjM5NDI4NTB9.9iFSH_5IANXEBFw_EpW7mC7JP9PJKkkmMv7zgA6gd8E


### Suppression d'un utilisateur a un event
PATCH https://playrfindr.herokuapp.com/api/event/53
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzOTQzOTY4LCJleHAiOjE2MjM5NDc1Njh9.UfU3CXpr6ZSo0Od8BH0wr6_3AIcNuIqUduTMWyJVwTA

### delete d'un utilisateur
DELETE https://playrfindr.herokuapp.com/api/profil/72



### Suppression d'un event
DELETE  http://localhost:4000/api/event/45
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQ1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjIzOTQ0OTUyLCJleHAiOjE2MjM5NDg1NTJ9.PMqNO3Q6RM38WCxI9F5kZIv4QvEs8FZ3-eHQSSkaowY

### Suppression d'un event
DELETE  https://playrfindr.herokuapp.com/api/event/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjQwMTQ2ODAsImV4cCI6MTYyNDAxODI4MH0.0_ogS_XQ298jLBLeQHyDgPD_j9Lhpqw39ke494VY0UI


### Delete d'un jeux d'une collection
DELETE http://localhost:4000/api/profil/3/collection/6
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2MjM3NTEzOTYsImV4cCI6MTYyMzc1NDk5Nn0.GaBew1SaWtLDL5ntO7ormhGdKSCKKbQT1bgWBP5mTpk

### Delete d'un jeux d'une collection
DELETE https://playrfindr.herokuapp.com/api/profil/1/collection/6



### Delete d'un message
DELETE http://localhost:4000/api/message/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjc1LCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjI0MDAyOTgxLCJleHAiOjE2MjQwMDY1ODF9.hNErfQAuSRzCnsmTmAJFjyHCSCDMN4ta83dn1wHulFI