### resource not found
GET http://localhost:4000/api/null

### Page d'acceuil
GET http://localhost:4000/api

### Récupération de tout les jeux
GET http://localhost:4000/api/jeux

### Récupération d'un jeu
GET http://localhost:4000/api/jeu/1


### Ajout d'un utilisateur
POST http://localhost:4000/api/inscription
Content-Type: application/json
{
    "firstname": "Dominique",
    "lastname": "Roux",
    "email": "aeerra@gmail.com",
    "password": "123456789",
    "passwordConfirm": "123456789",
    "birthdate": "1995-07-18",
    "department_id": 65
}

### Récuperation d'un utilisateur
POST http://localhost:4000/api/connexion
Content-Type: application/json

{
    "email": "dim.mart@gmail.com",
    "password": "1234569"
 
}